### ISSUE TITLE
custom EDID chromaticity values aren't picked up

### ISSUE THREAD

**Issue by aufkrawall** [ledoge/novideo_srgb#10] opened 2021-12-23 13:51 UTC
Hello,
I've changed chromaticity values for my EDID and installed it via CRU. However, novideo_srgb still reports the default EDID values:
![edid](https://user-images.githubusercontent.com/13510490/147249297-3a062a4f-95cb-459a-ad0e-64c58a5b90cd.png)

![info](https://user-images.githubusercontent.com/13510490/147249478-70f4d3f4-a3de-4ab8-9676-c1b2a313f803.png)

I wonder if I'm missing something? I also tried installing the custom EDID as monitor driver, it made no difference.
Thanks!

**Comment by ledoge** [comment] 2021-12-28 10:04
You're right, it was reading it directly from the monitor so overrides didn't work. Should be fixed now in v1.0 though (reboot is still required).

**Comment by aufkrawall** [comment] 2021-12-28 14:18
1.0 still detects the default EDID's values for me.
But not a big deal, as the new ICC profile option works. Wow, this is nothing but a game changer. Thank you so much for this! :)

Also the new gamma options works great and unlike with other APIs, Windows doesn't wreck color precision after e.g. suspend event. Does it also correct white point and gray scale according to the ICC profile?

Perhaps by default, it could apply gamma as specified by the 1D LUT that DisplayCal generates and is included in the ICC profile? E.g. I specified a black output level of 98% in DisplayCal to boost very dark tones a bit with gamma 2.4 (relative) and this is applied when Windows or CalibrationTools apply 1D LUT via GPU gamma ramps.

It's not really urgent, as you can just use CalibrationTools top tick the checkbox for dithering options, but I suppose it would also make sense to have controls about it also in your tool. :)
By default with 8 bit display output, there is no dithering active with Nvidia and thus banding when novideo_srgb lets the driver perform the conversions. When enabling (temporal) dithering, to my eyes it completely disappears:
![dither](https://user-images.githubusercontent.com/13510490/147574837-de1f0d07-654d-44fe-a6a7-985a38b3e4e5.png)
Some displays are said to have issues with temporal dithering (never seen this personally), so enforcing it by default perhaps wouldn't make everyone happy either (users can be such a demanding crowd :p ).

Still having to process what a great benefit your tool already is, it's really unbelievable!

**Comment by ledoge** [comment] 2021-12-28 16:34
>1.0 still detects the default EDID's values for me.

Hmmm, not really sure why that would happen, it worked on my machine. Maybe it fails to read it from the registry for some reason? idk

>Does it also correct white point and gray scale according to the ICC profile?

It basically applies a relative colorimetric transform, so the white point stays as it is, but the gray scale data is used, yes. 

>Perhaps by default, it could apply gamma as specified by the 1D LUT that DisplayCal generates and is included in the ICC profile?

Well, this is not entirely the target use for this tool and probably a bit of a niche use case, but I quickly threw something together and added a checkbox that should do what you want when enabled. Please try out the new v1.1 build and tell me if it works as expected. Note that you still have to select a gamma curve to be used to decode from gamma space to linear space and back again between the matrix transform, but there should only be a minor color difference between the options and no real grayscale difference.

>It's not really urgent, as you can just use CalibrationTools top tick the checkbox for dithering options, but I suppose it would also make sense to have controls about it also in your tool. :)

Good idea, it's not a priority right now but I'll look into it.

>Thank you so much for this! :)

Thank you for the feedback!

**Comment by aufkrawall** [comment] 2021-12-28 17:16
Thanks again!
Hm, I'd say it still looks like pure power curve. At least the used gamma test picture is still harder to recognize than with the 1D LUT with 98% black output offset by DisplayCal. Though I wonder if it is actually a good idea to rely on adjusting gamma/gray scale when it ignores white point entirely (even when the display is natively adjusted really close to 6500K?).
It'd be some kind of cherry on top if novideo_srgb could apply full blown 1D LUT via the apparently more reliable NV driver API. But I probably should not get greedy... ;)

Regarding customized chromaticity values in custom EDID: I'll check if it makes a difference how the EDID is installed, I've currently been doing it via custom monitor driver instead of the normal CRU registry hack. But I'm already happy anyway with the ICC profile parsing support. :)

**Comment by ledoge** [comment] 2021-12-28 17:28
>At least the used gamma test picture is still harder to recognize than with the 1D LUT with 98% black output offset by DisplayCal. 

Not sure why that would be... Just to make sure, you took an ICC profile that has such a curve as its VCGT calibration, loaded it into novideo_srgb and also checked the new bottom checkbox, yes? That should result in the display gamma being determined solely by the VCGT calibration and nothing else.

>Though I wonder if it is actually a good idea to rely on adjusting gamma/gray scale when it ignores white point entirely 

I wouldn't say that it's ignored, but it doesn't have to care about it because the transform matrix stored in the ICC profile itself is independent of the "real" white point (due to ICC profiles always being relative to D50 white). Additionally, the 3x 1D TRC and 3x 1D VCGT data is used, so you're still getting the full benefits of those parts of the ICC profile. But the remaining e.g. XYZ LUT parts cannot be used due to the GPU only supporting simple LUT-Matrix-LUT and not 3D LUT transforms. So as long as the display is well-behaved and (almost) linear, you are getting a "full" calibration with (probably) ≤1 average Delta E.

**Comment by aufkrawall** [comment] 2021-12-28 19:09
> Not sure why that would be... Just to make sure, you took an ICC profile that has such a curve as its VCGT calibration, loaded it into novideo_srgb and also checked the new bottom checkbox, yes? That should result in the display gamma being determined solely by the VCGT calibration and nothing else.

Yes, I've just checked again to be sure.

Attaching the test picture (viewed in non-color managed image viewer):
![DOOMEternalx64vk_2021_12_28_19_47_01_088](https://user-images.githubusercontent.com/13510490/147598628-f914d379-7ea2-4525-ac7a-946ef1dd6300.png)

Used ICC profile:
[icc.zip](https://github.com/ledoge/novideo_srgb/files/7786066/icc.zip)

It's definitely harder to spot with "Use selected gamma instead of TRC" checked compared to loading the included VCGT with Calibration Tools into GPU gamma ramps.

**Comment by ledoge** [comment] 2021-12-28 20:13
Interesting – unfortunately I'm not really sure what is causing this mismatch, as there are too many variables. Could be a bug in my code, a rounding error somewhere in hardware or software, or simply a difference in how VCGT values are handled vs the values set via this API. Assuming my code isn't broken, for now you should be able to achieve better results by using different gamma parameters in DisplayCAL, I guess.

**Comment by aufkrawall** [comment] 2021-12-28 20:53
Thanks. At some point I'll try with a quick calibration with 50% or 0% black output offset that should boost gamma a lot with my black level, to see if that makes a difference. But really not a pressing issue for me, life is not so bad with novideo_srgb + Calibration Tools at the same time.

**Comment by aufkrawall** [comment] 2021-12-29 14:44
Does BT.1886 in novideo_srgb boost gamma for you? I think it looks just like pure power 2.4 curve for me. When I let DisplayCal generate a 3D LUT with BT.1886 curve, it boosts gamma a lot since it has black output offset set to 0% (which seems to be the only difference to pure power gamma 2.4 curve, where is it set to 100%).

**Comment by ledoge** [comment] 2021-12-29 15:00
It is equivalent to pure 2.4 when the ICC profile has black point compensation built-in instead of encoding the real black point, which is unfortunately the case with DisplayCAL's default settings. It should work properly on a curves+matrix profile with black point compensation disabled.

**Comment by aufkrawall** [comment] 2021-12-29 15:08
Hm, the checkbox for black point compensation isn't checked for me by default with XYZ LUT + matrix profile type. Is it in some way adherent to that profile type regardless?

**Comment by ledoge** [comment] 2021-12-29 15:13
From my testing, yes. You can check for yourself by clicking the ℹ️ button to inspect the profile, selecting the tone response curve option in the dropdown and disabling the LUT checkbox. The curves start at (0, 0) instead of the actual black point on my XYZ LUT profile with black compensation disabled, but not on my curves+matrix profile.

**Comment by aufkrawall** [comment] 2021-12-29 15:24
It looks like this for me:
![gamma](https://user-images.githubusercontent.com/13510490/147677402-113950bb-e717-4364-aef0-92c5016d0f3b.png)

**Comment by ledoge** [comment] 2021-12-29 15:32
Need to disable the LUT checkbox to see the TRC values instead of the ones from the lookup tables.

**Comment by aufkrawall** [comment] 2021-12-29 15:34
Yes, sorry about that. It indeed starts at 0 with LUT unticked. Thanks, I'll create a new profile then with curves + matrix profile and black point compensation unchecked.

**Comment by aufkrawall** [comment] 2021-12-29 18:21
With curves + matrix profile and black point compensation unchecked, BT.1886 in novideo_srgb now boosts gamma as expected. However, gamma with "Use selected gamma instead of TRC" is still darker than VCGT via Calibration Tools (calibration was done again with 98% black output offset). Furthermore, there is now also a weird greenish color tint issue for dark tones when letting novideo_srgb do gamma calibration. This issue also is not there when using VCGT via Calibration Tools.

New ICC profile in curves + matrix format:
[G27q-20 #1 2021-12-29 18-11 D6500 2.4 M-S 3xCurve+MTX.zip](https://github.com/ledoge/novideo_srgb/files/7790126/G27q-20.1.2021-12-29.18-11.D6500.2.4.M-S.3xCurve%2BMTX.zip)

**Comment by ledoge** [comment] 2021-12-30 04:16
Thanks for the profile! The green tint seems to be caused by how DisplayCAL generates the 3 TRC curves, presumably trying to minimize overall deviation instead of preserving grayscale. You can use a Single curve + matrix profile instead, which should fix that.

Unfortunately, unless I did something wrong in my testing, it seems like the black crush is caused by insufficient precision in the GPU's color space conversion math. When I set the degamma LUT to linear, the color space conversion to a unity matrix, and the regamma LUT to the VCGT data (so effectively just loading the VCGT data), there was no black crush. However, adding a gamma function to the degamma and regamma LUT (as needed for color space conversions) then resulted in black crush again. Not really sure what could be done to work around this...

**Comment by aufkrawall** [comment] 2021-12-30 14:03
Thanks for investigating and sharing your findings.
Oddly, I could "fix" the green tint with a new calibration with more test patches (for which for whatever reason the drop down menu must be used in DisplayCal instead of the slider for curves + matrix). The green tint occured both with and without the TRC override checkbox afair.

Do you think it is safe to use novideo_srgb for gamut clamping + VCGT via GPU gamma ramps at the same time with regard to calibration accuracy?

**Comment by ledoge** [comment] 2021-12-30 14:16
You mean having the novideo_srgb clamp active, doing another calibration with it active and then loading those new VCGT values on top? Should be fine, as long as the API actually combines the values instead of replacing them (haven't tested this).

**Comment by aufkrawall** [comment] 2021-12-30 14:28
Thanks! So running another calibration with clamp active would generate a different VCGT? I was hoping that this wouldn't be necessary, since as a layman I'd think the VCGT from the first calibration is already meant to be applied after gamut clamping. But I might be misstaken. :)

**Comment by ledoge** [comment] 2021-12-30 14:54
The novideo_srgb clamp does include the VCGT data, but the actual VCGT remains linear since the data is included in the color space conversion set up via the NVAPI call (though it's probably physically the same thing as the VCGT inside the GPU? Not entirely sure.) So if you run another DisplayCAL calibration on top (assuming the driver even handles this properly), the resulting new VCGT data should ideally be linear. It might be worth a shot to see if it can further improve color accuracy/black crush caused by insufficient precision of the color space conversion pipeline, but other than that there would be no point.

**Comment by aufkrawall** [comment] 2021-12-31 22:44
I've run a 2nd calibrationwith clamp enabled, I think I couldn't tell the difference in a blind test.

However, it seems novideo_srgb's clamp is still slightly oversaturated?
![cal](https://user-images.githubusercontent.com/13510490/147840476-1bfaca16-a417-4c0b-83ad-8e53152598c8.png)

Accordingly with 3D LUT via ReShade on vs. off:
![witcher3_2021_12_31_23_33_22_544](https://user-images.githubusercontent.com/13510490/147840491-ed9040a6-534c-453c-9fa6-f3a16eb44461.png)

![witcher3_2021_12_31_23_33_17_826](https://user-images.githubusercontent.com/13510490/147840494-883a59ae-40a9-45dd-a42e-1f29c6492392.png)

**Comment by ledoge** [comment] 2021-12-31 22:51
Not really sure why that would happen... Can you post a verification report generated with the clamp enabled and with no ICC profile, i.e. with "Use simulation profile as display profile" enabled?

**Comment by aufkrawall** [comment] 2021-12-31 23:05
Sure. I selected to calibrate to relative gamma 2.2 in novideo_srgb when doing the verification. I didn't do that when running the 2nd calibration with clamp enabled.
[Measurement Report 3.8.9.3 — G27q-20 @ 0, 0, 2560x1440 — 2021-12-31 23-58.zip](https://github.com/ledoge/novideo_srgb/files/7797200/Measurement.Report.3.8.9.3.G27q-20.%40.0.0.2560x1440.2021-12-31.23-58.zip)

**Comment by ledoge** [comment] 2021-12-31 23:23
Well, judging from the report, the color accuracy should be basically perfect. Not sure how exactly the results of the profiling done with the clamp active (and the 3D LUT generated from it) can be explained, but I would guess that this anomaly is caused by the limitations of a lut-matrix-lut calibration (as opposed to a full 3D LUT one) and not due to a bug anywhere else, as I don't see how you could have delta e <1 for every measured patch otherwise.

**Comment by ledoge** [comment] 2022-01-01 14:28
I just pushed a new release with dither controls, please test it to see if everything works as it should.

**Comment by aufkrawall** [comment] 2022-01-01 14:46
From what I can tell, new dithering controls work fine. I set the display to 8 bit and banding disappeared after configuring it to 8 bit temporal in novideo_srgb (made sure that the checkbox in Calibration Tools was unticked). =)

I suppose it was 1.4 that made sRGB gamma correction available with "Use selected gamma instead of TRC" at the same time? It seems this fixes/honors the 98% black output offset of the VCGT, close-to-black crush is gone. :)

**Comment by ledoge** [comment] 2022-01-01 14:51
Nice, thanks!

That sRGB change was a few versions ago, as part of v1.2.

**Comment by aufkrawall** [comment] 2022-01-01 19:12
I've run a verification report with calibrated gamma (sRGB + VCGT data in novideo_srgb). I used the same verification properties (rel gamma 2.4, 98% black output offset) which I had used for the calibration. It seems to be really good, apart from extremely bright tones:
[Measurement Report 3.8.9.3 — G27q-20 @ 0, 0, 2560x1440 — 2022-01-01 19-47.zip](https://github.com/ledoge/novideo_srgb/files/7798098/Measurement.Report.3.8.9.3.G27q-20.%40.0.0.2560x1440.2022-01-01.19-47.zip)

So it seems this setting combination in novideo_srgb is really recommendable? I think actually more so than leaving "Use selected gamma instead of TRC" unchecked, as this always seems to cause a bit of black crush, even with both rel./ab. gamma 2.2 (unlike with VCGT via gamma ramps).

Now, for whatever weird reasons, the oversaturation is also visible in the same report. It's definitely the correct ICC profile used both in novideo_srgb and DisplayCal validation, that is unclamped with ~99% DCI-P3:
[G27q-20 #1 2021-12-29 20-50 D6500 2.4 M-S XYZLUT+MTX.zip](https://github.com/ledoge/novideo_srgb/files/7798110/G27q-20.1.2021-12-29.20-50.D6500.2.4.M-S.XYZLUT%2BMTX.zip)

**Comment by aufkrawall** [comment] 2022-01-02 02:55
Rerun calibration two times with single curve + matrix, the 2nd time with novideo_srgb clamp including gamma 2.4 calibration:
![gamut](https://user-images.githubusercontent.com/13510490/147864692-d184a4f1-e741-4068-a9c7-80fc0e380d7a.png)

So just user failure, yay! :)
This also prevents black crush when using gamma 2.2 calibration in novideo_srgb.
Turns out the weirdly high delta values are caused by the "Use selected gamma instead of TRC" (I perhaps should have taken the warning in brackets seriously.)

Do you think it would be possible to mimic DisplayCal's black output offset option in novideo_srgb?

**Comment by ledoge** [comment] 2022-01-02 08:35
Interesting results – the problem with that TRC option is that the resulting color space transform is kind of a hybrid between what you'd get in applications that don't support color management (only VCGT calibration) and in applications that do (the gamut stuff + the EOTF/TRC of both the source color space and your display). So it's not really surprising that you'd get weird results with it, but I guess it can be useful in some cases when you really want to apply the VCGT data as-is.

I've pushed a new release with support for custom black output offset, however, it only works with absolute gamma right now, as I couldn't get Wolfram Alpha to produce an analytical solution for relative gamma (the math probably gets too complicated). IIRC DisplayCAL uses an iterative approach to calculate the right value instead of doing it analytically.

**Comment by provanguard** [comment] 2022-01-02 09:34
@aufkrawall Could you please post the screenshots from your DisplayCAL settings used for calibration and the corresponding options selected in novideo_srgb? I am curious what options you are using exactly and what is your typical usage of the monitor.

**Comment by aufkrawall** [comment] 2022-01-02 16:41
> I've pushed a new release with support for custom black output offset, however, it only works with absolute gamma right now, as I couldn't get Wolfram Alpha to produce an analytical solution for relative gamma (the math probably gets too complicated). IIRC DisplayCAL uses an iterative approach to calculate the right value instead of doing it analytically.

Once again: Thanks a lot! It seems to work great. I'm not sure there is a noticeable difference for me with rel. vs. abs. gamma anyway. I've also run validation with it in DisplayCal and my delta values and gamma curve are still good (and rec709 volume is still nicely clamped :) ).

@provonguard In DisplayCal, I use
- default gamma 2.2 desktop profile as a base
- set whitepoint to 6500K (adjust colors in display OSD accordingly, make sure the display is correctly warmed up, i.e. check a few hours later that white point is unchanged)
- gamma to rel. 2.4 with 98% black output offset (probably doesn't matter anymore when using novideo_srgb for gamma calibration without VCGT, hopefully not counterproductive)
- calibration speed to medium (not sure if this isn't actually a waste of time when using gamma calibration with novideo_srgb)
- in profiling: single curve + matrix with black point compensation checkbox unticked
- perhaps select "default testchart" from the dropdown menu to run 79 patches with curve + matrix profile type

**Comment by provanguard** [comment] 2022-01-02 17:30
> gamma to rel. 2.4 with 98% black output offset (probably doesn't matter anymore when using novideo_srgb for gamma calibration without VCGT, hopefully not counterproductive)
 
Can I ask what does this do for you? What is your application usage?

**Comment by aufkrawall** [comment] 2022-01-02 17:55
> > gamma to rel. 2.4 with 98% black output offset (probably doesn't matter anymore when using novideo_srgb for gamma calibration without VCGT, hopefully not counterproductive)
> 
> Can I ask what does this do for you? What is your application usage?

It is just media consumer usecases, mostly under dimmed viewing conditions. Gamma is an intricate topic, it is not always clear what would be the correct display gamma for a given example. A lot of videos/games are produced for 2.4 display gamma, while others are for 2.2. Then there is also BT.1886 curve, wich afaik boosts gamma depending on the black level that is specified in the ICC profile (which results in 2.4 pure power curve with OLED blacks). This is why it's great than you can just switch gamma in novideo_srgb without hassle. 98% black output offset helps against near-black-crush with e.g. bad IPS black levels, while you can still have the more contrast rich look of gamma 2.4 at the same time with corresponding content.

**Comment by aufkrawall** [comment] 2022-01-03 19:45
Thanks for black output offset support also for rel. gamma! I have already stopped using VCGT via gamma ramps since you added the black output offset support for abs. gamma. No more need for bugged GPU gamma ramps on Windows, which is a another big relief. :)

Hm, I'm not sure if it's actually an issue of novideo_srgb that it doesn't recognize the adjusted chromaticity values in custom EDID. It rather seems either CRU or Windows don't really apply them accordingly, as chromaticity values are always reset to that of the default EDID when I save the active custom EDID as a file anew and inspect it in AW EDID Editor. Probably nothing to be done about it? Would be totally fine imho since there is ICC profile support.

**Comment by aufkrawall** [comment] 2022-01-09 14:24
I set gamma to absolute 2.4 in novideo_srgb (as with it, there should be 0 differences possible with regard to maths between DisplayCal and novideo_srgb?) and ran a 2nd calibration (accordingly with also gamma 2.4 abs. calibration for VCGT/target). When creating a 3D LUT without gamma calibration included and injecting it via ReShade, the differences vs. novideo_srgb clamp are very littley (mostly just the red tone of the archer's clothing):
![witcher3_2022_01_09_03_21_39_596](https://user-images.githubusercontent.com/13510490/148685988-0dfff248-6ffa-4016-bf98-da01c9d75f07.png)

![witcher3_2022_01_09_03_21_34_596](https://user-images.githubusercontent.com/13510490/148685991-936b3a7f-b7a2-432d-a19b-d38f8345d359.png)

Though when including gamma correction in the 3D LUT, the differences increase a bit:
![witcher3_2022_01_09_03_25_44_673](https://user-images.githubusercontent.com/13510490/148686068-689d8d95-854f-4a56-a582-13bfd2e22d12.png)

![witcher3_2022_01_09_03_25_52_527](https://user-images.githubusercontent.com/13510490/148686071-54570d51-3b24-4e86-8f74-675e30d055ec.png)

No idea if this is useful information, but hope it can't hurt to just drop it here. :)

Btw. Firefox does not work with an ICC profile in curve format with more than 34 profiling patches, at least that's the case for me with 79 patches. So probably scratch what I said earlier regarding increasing patches with that profile format if you want to use the profile also outside of novideo_srgb. :)

**Comment by aufkrawall** [comment] 2022-01-27 19:24
In case this may be of interest :) :
When running DisplayCal validation with display set to 8 instead of 10 bit, I'm getting lower ΔE*00 values, and especially significantly lower deviations from optimal gamma curve for some steps. So I think the conclusion is that novideo_srgb's processing is even better than I initially thought, but allegedly my display's 10 bit handling is poor (if it isn't Windows or the Nvidia driver).

**Comment by ledoge** [comment] 2022-01-27 19:35
Did you do the calibration/profiling with the display set to 10 bit or also to 8 bit? If there's some kind of (consistent) processing issue, I would expect it to only really affect the results when the bit depth used for validation differs from the one used earlier. Weird if that's not the case here.

And yes, feedback and observations like these are always welcome!

**Comment by aufkrawall** [comment] 2022-01-27 19:42
Yes, if I'm not mistaken, calibration was done with display set to 10 bit.

**Comment by theaspiringitpro** [comment] 2022-01-27 20:00
> In case this may be of interest :) : When running DisplayCal validation with display set to 8 instead of 10 bit, I'm getting lower ΔE*00 values, and especially significantly lower deviations from optimal gamma curve for some steps. So I think the conclusion is that novideo_srgb's processing is even better than I initially thought, but allegedly my display's 10 bit handling is poor (if it isn't Windows or the Nvidia driver).

I'd be interested in seeing those validation reports if possible. Perhaps just using 8-bit with dithering done within the novideo is the better choice than 10-bit (8-bit + TFRC)?

**Comment by aufkrawall** [comment] 2022-01-27 20:33
[reports.zip](https://github.com/ledoge/novideo_srgb/files/7953614/reports.zip)
I probably should re-run calibration with 8 bit, just to be safe.

**Comment by theaspiringitpro** [comment] 2022-01-27 20:51
> [reports.zip](https://github.com/ledoge/novideo_srgb/files/7953614/reports.zip) I probably should re-run calibration with 8 bit, just to be safe.

Thanks for the reports. If I had to guess, the lower ΔE*00 values you're seeing were likely caused by variance between validation reports. From my experience, Spyder's are quite inaccurate in general. With the old SpyderX I was using for less than a week I saw variance in ΔE*00 values & contrast pretty much every time I ran a validation. 

The next time I run a calibration I'll be sure to test 8-bit vs 10-bit. Currently using a calibrite colorchecker display pro.

**Comment by aufkrawall** [comment] 2022-01-27 20:56
I ran the reports in direct succession and so far I've found measurement results reliable (no weird random deviations, at least not noteworthy) afaict.

**Comment by aufkrawall** [comment] 2022-01-28 20:57
Profiles + validation reports for XYZ + MTX, curves + MTX and single curve + MTX formats (8 bit + temporal dithering):
[profiles.zip](https://github.com/ledoge/novideo_srgb/files/7961772/profiles.zip)

XYZ has highest deviations, whereas single curve lowest. The lower gamma deviations vs. 10 bit are confirmed, so I suppose my display slightly screws up internal gamma processing with 10 bit.

**Comment by theaspiringitpro** [comment] 2022-01-28 22:12
> Profiles + validation reports for XYZ + MTX, curves + MTX and single curve + MTX formats (8 bit + temporal dithering): [profiles.zip](https://github.com/ledoge/novideo_srgb/files/7961772/profiles.zip)
> 
> XYZ has highest deviations, whereas single curve lowest. The lower gamma deviations vs. 10 bit are confirmed, so I suppose my display slightly screws up internal gamma processing with 10 bit.

Was excited to check the reports but looks like the files are corrupted. 

Also, do you have a true 10-bit display or is it 8-bit + FRC?

**Comment by aufkrawall** [comment] 2022-01-28 22:18
Aren't corrupted, try this 7-Zip fork: https://github.com/mcmilk/7-Zip-zstd
Forgot what the typical compression algo for zips is, as glorious GitHub doesn't allow .7z attachment extension.

Hardly any display is said to be native 10 bit instead of 8 bit + FRC, I haven't checked with colorimeter.

**Comment by ledoge** [comment] 2022-01-29 11:16
Thanks for the reports! I don't understand why/how a single curve profile would be better than the other options though... Could maybe also be caused by the display shifting a bit and/or measurement errors? I think it would be interesting to see if you'd still get similar results with 3 different types of profiles created from the same measurement data (File -> Create profile from measurement data...).

**Comment by aufkrawall** [comment] 2022-02-03 15:06
Sorry for the delay, I'll try to get to it at some point. Though when saving a profile as a different type, the calibration results reported by DisplayCal for the new profiles already differ slightly (because it takes less patches into consideration when converting to curve format from XYZ LUT?).
I can't validate my previous profiles anymore, as I had to slightly re-calibrate native whitepoint for 8 bit/144Hz.

But yes, there already is some continuous deviation when e.g. examining whitepoint, there are constant changes within a range of ~0.2ΔE*00. No idea if this is normal or Spyder deficiencies.

**Closed** 2022-07-31 12:56 UTC
